package xyz.ocean.mobile.data

import xyz.ocean.mobile.core.OceanlnCore
import xyz.ocean.mobile.core.Activity as CoreActivity
import xyz.ocean.mobile.core.PoolStats as CorePoolStats

// Android core binding: wraps the UniFFI-generated `OceanlnCore` (JNA) from
// ../core/build-android.sh. Every value the UI renders originates here — node
// balances and payments from the in-process Lexe node, mining stats from
// OCEAN's public API, the BTC/USD rate from mempool.space. Nothing is
// synthesised locally.
//
// NOTE: this file references xyz.ocean.mobile.core.*, which is GENERATED by
// `mobile/core/build-android.sh` into androidMain. Run that before building the
// Android app, or this source won't resolve. See mobile/README.md.
actual fun createCoreRepository(appDataDir: String): WalletRepository =
    CoreWalletRepository(OceanlnCore(appDataDir))

/** Rows requested per activity refresh. */
private const val ACTIVITY_LIMIT: UShort = 200u

private class CoreWalletRepository(private val core: OceanlnCore) : WalletRepository {
    // Read per access, not captured once: a cached "now" freezes every
    // relative timestamp in the app at the moment the repo was constructed.
    override val nowMs: Long get() = System.currentTimeMillis()

    // One call serves offer / miningAddress / isWalletConfigured — those are
    // interface defaults over this.
    override suspend fun status(): WalletStatus = core.status().let {
        WalletStatus(
            configured = it.configured,
            miningAddress = it.miningAddress,
            offer = it.offer,
        )
    }

    override suspend fun generateWallet(): WalletSetup {
        val result = core.generate()
        return WalletSetup(result.mnemonic, result.miningAddress)
    }

    override suspend fun restoreWallet(mnemonic: String): WalletSetup {
        val result = core.importSeed(mnemonic, false)
        completeWalletSetup()
        // A restored wallet's phrase is already in the user's hands — there is
        // nothing for them to write down, so the backup step is satisfied.
        core.confirmBackup()
        return WalletSetup(null, result.miningAddress)
    }

    override suspend fun revealSeed(): String = core.revealSeed().mnemonic
    override suspend fun isBackupConfirmed(): Boolean = core.backupConfirmed()

    override suspend fun completeWalletSetup() {
        core.initWallet(null)
        if (core.status().offer == null) {
            core.createOffer("OCEAN Lightning mobile", null)
        }
    }

    override suspend fun confirmBackup() = core.confirmBackup()

    override suspend fun payableAmountSats(payable: String): Long? =
        core.payableAmountSats(payable)?.toLong()

    override suspend fun createInvoice(amountSats: Long?, description: String?): String =
        core.createInvoice(amountSats?.toULong(), description)

    override suspend fun pay(payable: String, amountSats: Long?, note: String?): PaymentResult {
        val result = core.pay(payable, amountSats?.toULong(), note)
        return PaymentResult(result.id, result.amountSats.toLong())
    }

    override suspend fun pool(): PoolStats? {
        val address = core.status().miningAddress ?: return null
        return core.poolStats(address).toUi()
    }

    // `balances()` is an interface default over this, so the Wallet and Node
    // screens share one `nodeStatus()` round-trip instead of making two.
    override suspend fun nodeInfo(): NodeInfo {
        val n = core.nodeStatus()
        return NodeInfo(
            nodePk = n.nodePk,
            channels = n.numChannels.toInt(),
            usableChannels = n.numUsableChannels.toInt(),
            lightningTotalSats = n.lightningTotalSats.toLong(),
            lightningSendableSats = n.lightningSendableSats.toLong(),
            onchainTotalSats = n.onchainTotalSats.toLong(),
            onchainTrustedSats = n.onchainTrustedSats.toLong(),
            totalBalanceSats = n.totalBalanceSats.toLong(),
        )
    }

    // `listPayments` takes a UShort; a bare `200u` literal is a UInt.
    override suspend fun activity(): List<Tx> =
        core.listPayments(ACTIVITY_LIMIT).map { it.toTx() }

    override suspend fun btcUsd(): Double = core.btcUsd()
}

private fun CorePoolStats.toUi(): PoolStats = PoolStats(
    hashrate300s = hashrate300s,
    hashrate3600s = hashrate3600s,
    hashrate10800s = hashrate10800s,
    hashrate86400s = hashrate86400s,
    activeWorkers = activeWorkers.toInt(),
    lastShareTs = lastShareTs,
    unpaidSats = unpaidSats.toLong(),
    estPayoutNextBlockSats = estPayoutNextBlockSats.toLong(),
    estEarnNextBlockSats = estEarnNextBlockSats.toLong(),
    totalPaidSats = totalPaidSats.toLong(),
    lifetimeSats = lifetimeSats.toLong(),
    tidesShares = tidesShares,
    poolTidesShares = poolTidesShares,
    sharePct = sharePct,
    poolActiveUsers = poolActiveUsers.toLong(),
    poolActiveWorkers = poolActiveWorkers.toLong(),
    networkDifficulty = networkDifficulty,
    addressUnknown = addressUnknown,
)

private fun CoreActivity.toTx(): Tx = Tx(
    id = id,
    dir = if (direction == "in") Dir.IN else Dir.OUT,
    rail = if (rail == "ln") Rail.LN else Rail.ONCHAIN,
    amt = amountSats.toLong(),
    status = when (status) {
        "settled" -> TxStatus.SETTLED
        "failed" -> TxStatus.FAILED
        else -> TxStatus.PENDING
    },
    tsMs = finalizedAtMs,
    // The detail sheet's absolute date. Without this it rendered empty for
    // every live payment.
    tsIso = isoUtc(finalizedAtMs),
    party = counterparty ?: (if (isOcean) "OCEAN-format payment" else "Unknown"),
    note = note,
    offer = offer != null || isOcean,
    payerNote = note,
    noteMatch = isOcean,
    fee = feeSats.toLong(),
    hash = paymentHash,
    preimage = preimage,
    txid = txid,
    oceanBlockHeight = blockHeight?.toLong(),
)
