package xyz.ocean.mobile.data

import xyz.ocean.mobile.core.OceanlnCore
import xyz.ocean.mobile.core.Activity as CoreActivity

// Android core binding: wraps the UniFFI-generated `OceanlnCore` (JNA) from
// ../core/build-android.sh. Live node data (balances, activity) comes from the
// Rust core; pool/worker stats stay on mock here (they come from the ocean.xyz
// pool API, not the node — a follow-up).
//
// NOTE: this file references xyz.ocean.mobile.core.*, which is GENERATED by
// `mobile/core/build-android.sh` into androidMain. Run that before building the
// Android app, or this source won't resolve. See mobile/README.md.
actual fun createCoreRepository(appDataDir: String): WalletRepository? =
    CoreWalletRepository(OceanlnCore(appDataDir))

private class CoreWalletRepository(private val core: OceanlnCore) : WalletRepository {
    // Relative times are computed against the device clock for live data.
    override val nowMs: Long = System.currentTimeMillis()
    override val offer: String = core.status().offer ?: Mock.offer

    override suspend fun pool(): PoolStats = Mock.pool
    override suspend fun workers(): List<Worker> = Mock.workers

    override suspend fun balances(): Balances {
        val n = core.nodeStatus()
        return Balances(
            channel = n.lightningTotalSats.toLong(),
            capacity = maxOf(n.lightningTotalSats.toLong(), 1L),
            onchain = n.onchainTotalSats.toLong(),
        )
    }

    override suspend fun activity(): List<Tx> =
        core.listPayments(200u).map { it.toTx() }
}

private fun CoreActivity.toTx(): Tx = Tx(
    id = id,
    dir = if (direction == "in") Dir.IN else Dir.OUT,
    rail = if (rail == "ln") Rail.LN else Rail.ONCHAIN,
    amt = amountSats.toLong(),
    status = when (status) {
        "settled" -> TxStatus.SETTLED
        "failed" -> TxStatus.FAILED
        else -> TxStatus.PENDING
    },
    tsMs = finalizedAtMs,
    party = counterparty ?: (if (isOcean) "OCEAN" else "Unknown"),
    note = note,
    offer = offer != null || isOcean,
    payerNote = note,
    noteMatch = isOcean,
    fee = feeSats.toLong(),
    hash = paymentHash,
    preimage = preimage,
    txid = txid,
)
